//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decko
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public long id { get; set; }
        public Nullable<int> multiverseID { get; set; }
        public string setcode { get; set; }
        public string layout { get; set; }
        public string typeline { get; set; }
        public string type { get; set; }
        public string subtype { get; set; }
        public string name { get; set; }
        public string originalTypeline { get; set; }
        public decimal cmc { get; set; }
        public string rarity { get; set; }
        public string artist { get; set; }
        public string color { get; set; }
        public string cost { get; set; }
        public string text { get; set; }
        public string originalText { get; set; }
        public string flavor { get; set; }
        public string imageName { get; set; }
        public string power { get; set; }
        public string toughness { get; set; }
    }
}
