//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decko
{
    using System;
    using System.Collections.Generic;
    
    public partial class deck
    {
        public string id { get; set; }
        public string folderName { get; set; }
        public string name { get; set; }
        public string userID { get; set; }
        public string format { get; set; }
        public string decklist { get; set; }
        public string sideboard { get; set; }
        public string parentID { get; set; }
        public string version { get; set; }
        public System.DateTime postDate { get; set; }
    }
}
