//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decko
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long id { get; set; }
        public string username { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string dci { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string uid { get; set; }
        public bool admin { get; set; }
        public string regIP { get; set; }
        public System.DateTime updateDate { get; set; }
        public string gender { get; set; }
    }
}
